# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/isaacjetsonnano/source/detectnet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/isaacjetsonnano/source/detectnet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/isaacjetsonnano/source/detectnet/CMakeFiles /home/isaacjetsonnano/source/detectnet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/isaacjetsonnano/source/detectnet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my-recognition

# Build rule for target.
my-recognition: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my-recognition
.PHONY : my-recognition

# fast build rule for target.
my-recognition/fast:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/build
.PHONY : my-recognition/fast

src/detectnet.o: src/detectnet.cpp.o

.PHONY : src/detectnet.o

# target to build an object file
src/detectnet.cpp.o:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/detectnet.cpp.o
.PHONY : src/detectnet.cpp.o

src/detectnet.i: src/detectnet.cpp.i

.PHONY : src/detectnet.i

# target to preprocess a source file
src/detectnet.cpp.i:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/detectnet.cpp.i
.PHONY : src/detectnet.cpp.i

src/detectnet.s: src/detectnet.cpp.s

.PHONY : src/detectnet.s

# target to generate assembly for a file
src/detectnet.cpp.s:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/detectnet.cpp.s
.PHONY : src/detectnet.cpp.s

src/followBottle/driveRobot.o: src/followBottle/driveRobot.cpp.o

.PHONY : src/followBottle/driveRobot.o

# target to build an object file
src/followBottle/driveRobot.cpp.o:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/driveRobot.cpp.o
.PHONY : src/followBottle/driveRobot.cpp.o

src/followBottle/driveRobot.i: src/followBottle/driveRobot.cpp.i

.PHONY : src/followBottle/driveRobot.i

# target to preprocess a source file
src/followBottle/driveRobot.cpp.i:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/driveRobot.cpp.i
.PHONY : src/followBottle/driveRobot.cpp.i

src/followBottle/driveRobot.s: src/followBottle/driveRobot.cpp.s

.PHONY : src/followBottle/driveRobot.s

# target to generate assembly for a file
src/followBottle/driveRobot.cpp.s:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/driveRobot.cpp.s
.PHONY : src/followBottle/driveRobot.cpp.s

src/followBottle/findClosest.o: src/followBottle/findClosest.cpp.o

.PHONY : src/followBottle/findClosest.o

# target to build an object file
src/followBottle/findClosest.cpp.o:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/findClosest.cpp.o
.PHONY : src/followBottle/findClosest.cpp.o

src/followBottle/findClosest.i: src/followBottle/findClosest.cpp.i

.PHONY : src/followBottle/findClosest.i

# target to preprocess a source file
src/followBottle/findClosest.cpp.i:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/findClosest.cpp.i
.PHONY : src/followBottle/findClosest.cpp.i

src/followBottle/findClosest.s: src/followBottle/findClosest.cpp.s

.PHONY : src/followBottle/findClosest.s

# target to generate assembly for a file
src/followBottle/findClosest.cpp.s:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/findClosest.cpp.s
.PHONY : src/followBottle/findClosest.cpp.s

src/followBottle/floatToInt.o: src/followBottle/floatToInt.cpp.o

.PHONY : src/followBottle/floatToInt.o

# target to build an object file
src/followBottle/floatToInt.cpp.o:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/floatToInt.cpp.o
.PHONY : src/followBottle/floatToInt.cpp.o

src/followBottle/floatToInt.i: src/followBottle/floatToInt.cpp.i

.PHONY : src/followBottle/floatToInt.i

# target to preprocess a source file
src/followBottle/floatToInt.cpp.i:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/floatToInt.cpp.i
.PHONY : src/followBottle/floatToInt.cpp.i

src/followBottle/floatToInt.s: src/followBottle/floatToInt.cpp.s

.PHONY : src/followBottle/floatToInt.s

# target to generate assembly for a file
src/followBottle/floatToInt.cpp.s:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/floatToInt.cpp.s
.PHONY : src/followBottle/floatToInt.cpp.s

src/followBottle/initI2C.o: src/followBottle/initI2C.cpp.o

.PHONY : src/followBottle/initI2C.o

# target to build an object file
src/followBottle/initI2C.cpp.o:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/initI2C.cpp.o
.PHONY : src/followBottle/initI2C.cpp.o

src/followBottle/initI2C.i: src/followBottle/initI2C.cpp.i

.PHONY : src/followBottle/initI2C.i

# target to preprocess a source file
src/followBottle/initI2C.cpp.i:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/initI2C.cpp.i
.PHONY : src/followBottle/initI2C.cpp.i

src/followBottle/initI2C.s: src/followBottle/initI2C.cpp.s

.PHONY : src/followBottle/initI2C.s

# target to generate assembly for a file
src/followBottle/initI2C.cpp.s:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/initI2C.cpp.s
.PHONY : src/followBottle/initI2C.cpp.s

src/followBottle/intToFloat.o: src/followBottle/intToFloat.cpp.o

.PHONY : src/followBottle/intToFloat.o

# target to build an object file
src/followBottle/intToFloat.cpp.o:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/intToFloat.cpp.o
.PHONY : src/followBottle/intToFloat.cpp.o

src/followBottle/intToFloat.i: src/followBottle/intToFloat.cpp.i

.PHONY : src/followBottle/intToFloat.i

# target to preprocess a source file
src/followBottle/intToFloat.cpp.i:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/intToFloat.cpp.i
.PHONY : src/followBottle/intToFloat.cpp.i

src/followBottle/intToFloat.s: src/followBottle/intToFloat.cpp.s

.PHONY : src/followBottle/intToFloat.s

# target to generate assembly for a file
src/followBottle/intToFloat.cpp.s:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/intToFloat.cpp.s
.PHONY : src/followBottle/intToFloat.cpp.s

src/followBottle/intToInt.o: src/followBottle/intToInt.cpp.o

.PHONY : src/followBottle/intToInt.o

# target to build an object file
src/followBottle/intToInt.cpp.o:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/intToInt.cpp.o
.PHONY : src/followBottle/intToInt.cpp.o

src/followBottle/intToInt.i: src/followBottle/intToInt.cpp.i

.PHONY : src/followBottle/intToInt.i

# target to preprocess a source file
src/followBottle/intToInt.cpp.i:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/intToInt.cpp.i
.PHONY : src/followBottle/intToInt.cpp.i

src/followBottle/intToInt.s: src/followBottle/intToInt.cpp.s

.PHONY : src/followBottle/intToInt.s

# target to generate assembly for a file
src/followBottle/intToInt.cpp.s:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/intToInt.cpp.s
.PHONY : src/followBottle/intToInt.cpp.s

src/followBottle/motorDrive.o: src/followBottle/motorDrive.cpp.o

.PHONY : src/followBottle/motorDrive.o

# target to build an object file
src/followBottle/motorDrive.cpp.o:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/motorDrive.cpp.o
.PHONY : src/followBottle/motorDrive.cpp.o

src/followBottle/motorDrive.i: src/followBottle/motorDrive.cpp.i

.PHONY : src/followBottle/motorDrive.i

# target to preprocess a source file
src/followBottle/motorDrive.cpp.i:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/motorDrive.cpp.i
.PHONY : src/followBottle/motorDrive.cpp.i

src/followBottle/motorDrive.s: src/followBottle/motorDrive.cpp.s

.PHONY : src/followBottle/motorDrive.s

# target to generate assembly for a file
src/followBottle/motorDrive.cpp.s:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/src/followBottle/motorDrive.cpp.s
.PHONY : src/followBottle/motorDrive.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... my-recognition"
	@echo "... edit_cache"
	@echo "... src/detectnet.o"
	@echo "... src/detectnet.i"
	@echo "... src/detectnet.s"
	@echo "... src/followBottle/driveRobot.o"
	@echo "... src/followBottle/driveRobot.i"
	@echo "... src/followBottle/driveRobot.s"
	@echo "... src/followBottle/findClosest.o"
	@echo "... src/followBottle/findClosest.i"
	@echo "... src/followBottle/findClosest.s"
	@echo "... src/followBottle/floatToInt.o"
	@echo "... src/followBottle/floatToInt.i"
	@echo "... src/followBottle/floatToInt.s"
	@echo "... src/followBottle/initI2C.o"
	@echo "... src/followBottle/initI2C.i"
	@echo "... src/followBottle/initI2C.s"
	@echo "... src/followBottle/intToFloat.o"
	@echo "... src/followBottle/intToFloat.i"
	@echo "... src/followBottle/intToFloat.s"
	@echo "... src/followBottle/intToInt.o"
	@echo "... src/followBottle/intToInt.i"
	@echo "... src/followBottle/intToInt.s"
	@echo "... src/followBottle/motorDrive.o"
	@echo "... src/followBottle/motorDrive.i"
	@echo "... src/followBottle/motorDrive.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

